listName = ['Chris', 'Claire', 'Whitney']
print( 'Before inserting', listName)
listName.insert(0,'Erin')
print('After inerseting', listName)
listName.insert(3,'Cody')
print('Inserting middle of list', listName)
listName.append('Brian')
print('Appending', listName) 
popped_listName = listName.pop()
removed_List=listName.pop()
removed_List=listName.pop()
removed_List=listName.pop()

print('New poped list', removed_List)
print('my new list', listName)
